apiVersion: batch/v1
kind: CronJob
metadata:
  name: min-backup
  namespace: nginx
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: min-backup
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup-container
              image: busybox
              command:
                - sh
                - -c
                - >
                  echo "backup start";
                  mkdir -p /backup &&
                  mkdir -p /data &&
                  cp -r /demo-data/ /backup &&
                  echo "backup complete";
              volumeMounts:
                - name: data-volume
                  mountPath: /demo-data
                - name: backup-volume
                  mountPath: /backup
          volumes:
            - name: data-volume
              hostPath:
                path: /demo-data
                type: DirectoryOrCreate
            - name: backup-volume
              hostPath:
                path: /backup-data
                type: DirectoryOrCreate
